# Generated by Django 4.1.4 on 2022-12-19 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertScript',
            fields=[
                ('creator', models.CharField(max_length=50, verbose_name='creator')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('uniqueId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('alertName', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('creator', models.CharField(max_length=50, verbose_name='creator')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('uniqueId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stateName', models.CharField(max_length=50, unique=True)),
                ('stateType', models.CharField(choices=[('Start Node', 'Start Node'), ('Normal Node', 'Normal Node'), ('End Node', 'End Node')], max_length=50)),
                ('group', models.ManyToManyField(blank=True, to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('creator', models.CharField(max_length=50, verbose_name='creator')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('uniqueId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('notices', models.CharField(blank=True, max_length=50)),
                ('group', models.ManyToManyField(blank=True, to='auth.group')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('creator', models.CharField(max_length=50, verbose_name='creator')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('uniqueId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('conditions', models.CharField(blank=True, max_length=5000, null=True)),
                ('alertMethods', models.ManyToManyField(blank=True, to='workflow.alertscript')),
                ('destinationState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationState', to='workflow.state')),
                ('startState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitionsState', to='workflow.state')),
                ('workflow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.workflow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='state',
            name='workflow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.workflow'),
        ),
    ]
